name: ache
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alembic=1.15.2
  - blas=2.131
  - blas-devel=3.9.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - expat=2.7.1
  - greenlet=3.1.1
  - importlib-metadata=8.6.1
  - joblib=1.5.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.29
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - mako=1.3.10
  - markupsafe=3.0.2
  - ncurses=6.4
  - nomkl=3.0
  - numba=0.61.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openssl=3.0.16
  - optuna=4.3.0
  - packaging=25.0
  - pandas=2.2.3
  - pip=25.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - shap=0.46.0
  - six=1.17.0
  - slicer=0.0.8
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tqdm=4.67.1
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
